name: Example usage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        
    # https://github.com/appleboy/scp-action
    - name: copy file to our server
      uses: appleboy/scp-action@master
      with:
        host: 95.217.163.190
        username: HWS
        port: 2222
        password: ${{ secrets.PASSWORD }}
        source: "*"
        target: "/var/lib/docker/volumes/www/_data"
        rm: true
