name: Example usage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        
    # https://github.com/appleboy/scp-action
    - name: copy file to our server
      uses: appleboy/scp-action@master
      with:
        host: 95.217.163.190
        username: hws
        port: 2222
        password: ${{ secrets.PASSWORD }}
        source: "*"
        target: "/home/hws/deployment"
        rm: true

    # https://github.com/appleboy/ssh-action
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 95.217.163.190
        username: hws
        port: 2222
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/hws/echo
          ${{ secrets.PASSWORD }} | sudo -S mv -f ./deployment/* /var/lib/docker/volumes/www/_data
    
    # https://github.com/appleboy/ssh-action
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 95.217.163.190
        username: hws
        port: 2222
        password: ${{ secrets.PASSWORD }}
        script: docker run --rm --volume www:/app composer install

